SELECT ADDRESS
FROM STUDIO
WHERE NAME = 'MGM';

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME = 'Sandra Bullock';

SELECT DISTINCT S.STARNAME
FROM STARSIN S
JOIN MOVIE M ON S.MOVIETITLE = M.TITLE AND S.MOVIEYEAR = M.YEAR
WHERE M.YEAR = 1980 AND M.TITLE LIKE '%Empire%';

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000;

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M' OR ADDRESS LIKE '%Malibu%';