-- 1.
-- solution 1
SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000

INTERSECT

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'f'

-- solution 2
SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'f' AND NAME IN (SELECT NAME
								FROM MOVIEEXEC
								WHERE NETWORTH > 10000000)

-- 2.
-- solution 1
SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME
				   FROM MOVIEEXEC)

-- solution 2
SELECT NAME
FROM MOVIESTAR EXCEPT (SELECT NAME 
					   FROM MOVIEEXEC)

--------------------------------------

-- 1.
SELECT DISTINCT maker
FROM product
WHERE model IN (SELECT model
				FROM pc
				WHERE speed >= 500)

