
SELECT STARNAME
FROM STARSIN si
JOIN MOVIESTAR ms ON ms.NAME = si.STARNAME
WHERE ms.GENDER = 'f' AND si.MOVIETITLE = 'Titanic'

SELECT TITLE
FROM MOVIE
WHERE STUDIONAME = 'Universal' AND YEAR > 2000

SELECT STARNAME
FROM STARSIN si
JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
WHERE m.STUDIONAME = 'Warner Bros' AND m.YEAR = 2010

SELECT TITLE
FROM MOVIE 
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE = 'Star Wars')

------------------------

SELECT DISTINCT si.STARNAME
FROM STARSIN si
JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
JOIN MOVIESTAR ms ON ms.NAME = si.STARNAME
WHERE m.STUDIONAME = 'MGM' AND ms.GENDER = 'm'

SELECT title
FROM MOVIE
WHERE LENGTH > ALL (SELECT LENGTH  
				FROM MOVIE
				WHERE STUDIONAME = 'Paramount')

SELECT distinct si1.STARNAME
FROM STARSIN si1
JOIN STARSIN si2 on si1.STARNAME = si2.STARNAME and si1.MOVIETITLE != si2.MOVIETITLE and si1.MOVIEYEAR != si2.MOVIEYEAR

SELECT DISTINCT si1.STARNAME
FROM STARSIN si1
WHERE EXISTS (
	SELECT 1
	FROM STARSIN si2
	WHERE si1.STARNAME = si2.STARNAME
		AND (si1.MOVIETITLE != si2.MOVIETITLE AND si1.MOVIEYEAR != si2.MOVIEYEAR))

select DISTINCT si1.STARNAME
from STARSIN si1
join MOVIE m1 ON m1.TITLE = si1.MOVIETITLE and m1.YEAR = si1.MOVIEYEAR
where exists (
	select 1
	from STARSIN si2
	join MOVIE m2 ON m2.TITLE = si2.MOVIETITLE and m2.YEAR = si2.MOVIEYEAR
	where si1.STARNAME = si2.STARNAME
		and (m1.STUDIONAME != m2.STUDIONAME))

SELECT si.STARNAME
FROM STARSIN si
JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
GROUP BY si.STARNAME
HAVING COUNT (DISTINCT m.STUDIONAME) >= 2

SELECT si.STARNAME, m.LENGTH
FROM STARSIN si
JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
WHERE m.LENGTH = (SELECT max(length) FROM MOVIE)

SELECT si.STARNAME
FROM STARSIN si
JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
WHERE M.STUDIONAME = 'Warner Bros'

SELECT SUM(LENGTH) / COUNT (TITLE)
FROM MOVIE

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT SUM(LENGTH) / COUNT (TITLE)
				FROM MOVIE)

SELECT si.STARNAME
FROM STARSIN si
JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
JOIN MOVIESTAR ms ON ms.NAME = si.STARNAME
WHERE ms.GENDER = 'f' AND m.STUDIONAME != 'Universal'

-->

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'f'
AND NAME NOT IN (
	SELECT si.STARNAME
	FROM STARSIN si
	JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
	WHERE m.STUDIONAME = 'MGM')

SELECT TITLE
FROM MOVIE
WHERE LENGTH > ALL (SELECT LENGTH
					FROM MOVIE
					WHERE STUDIONAME = 'Disney')
--
SELECT LENGTH
FROM MOVIE
ORDER BY LENGTH DESC

SELECT si1.STARNAME
FROM STARSIN si1
WHERE EXISTS (SELECT 1
			  FROM STARSIN si2
			  WHERE si1.STARNAME = si2.STARNAME 
				and si1.MOVIETITLE = si2.MOVIETITLE 
				and si1.MOVIEYEAR != si2.MOVIEYEAR)

SELECT si1.STARNAME
FROM STARSIN si1
JOIN STARSIN si2 ON si2.STARNAME = si1.STARNAME AND
					si1.MOVIETITLE = si2.MOVIETITLE AND
					si1.MOVIEYEAR != si2.MOVIEYEAR

-- 4.
SELECT s.NAME, m.TITLE
FROM STUDIO s
LEFT JOIN MOVIE m ON m.STUDIONAME = s.NAME

SELECT me.NAME
FROM MOVIEEXEC me
LEFT JOIN MOVIE m ON me.CERT# = m.PRODUCERC#
WHERE m.TITLE IS NULL

SELECT ms.NAME, m.TITLE, m.STUDIONAME
FROM MOVIESTAR ms
LEFT JOIN STARSIN si ON si.STARNAME = ms.NAME
LEFT JOIN MOVIE m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR

SELECT m.TITLE, me.NAME
FROM MOVIE m
LEFT JOIN MOVIEEXEC me ON me.CERT# = m.PRODUCERC#
