-- 1.
SELECT m.STUDIONAME, s.STARNAME
FROM MOVIE AS m
JOIN STARSIN AS s ON s.MOVIETITLE = m.TITLE AND s.MOVIEYEAR = m.YEAR
ORDER BY m.STUDIONAME

-- 2.
SELECT DISTINCT me.NAME
FROM MOVIE AS m
JOIN STARSIN AS s ON s.MOVIETITLE = m.TITLE AND s.MOVIEYEAR = m.YEAR
JOIN MOVIEEXEC AS me ON m.PRODUCERC# = me.CERT#
WHERE s.STARNAME = 'Harrison Ford'

-- 3.
SELECT DISTINCT ms.NAME AS Name
FROM MOVIESTAR AS ms
JOIN STARSIN AS si ON si.STARNAME = ms.NAME
JOIN MOVIE AS m ON m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
WHERE ms.GENDER = 'f' AND m.STUDIONAME = 'MGM'

-- 4.
SELECT me.NAME, m.TITLE
FROM MOVIE AS m
JOIN MOVIEEXEC AS me ON me.CERT# = m.PRODUCERC#
WHERE m.PRODUCERC# IN (SELECT PRODUCERC#
					   FROM MOVIE
					   WHERE TITLE = 'Star Wars')

-- 5.
SELECT m.TITLE, m.YEAR, me.NAME
FROM MOVIE AS m
LEFT JOIN MOVIEEXEC AS me ON me.CERT# = m.PRODUCERC#

-- 6.
SELECT m.TITLE, m.YEAR, me.NAME, s.NAME, s.ADDRESS
FROM MOVIE AS m
LEFT JOIN MOVIEEXEC AS me ON m.PRODUCERC# = me.CERT#
LEFT JOIN STUDIO AS s ON m.STUDIONAME = s.NAME

-- 7.
SELECT ms.NAME
FROM MOVIESTAR AS ms
LEFT JOIN STARSIN AS si ON ms.NAME = si.STARNAME
WHERE si.MOVIETITLE IS NULL

---------------------------------------

-- 1.
SELECT p.model, pc.price
FROM product AS p
LEFT JOIN pc AS pc ON p.model = pc.model
WHERE p.type = 'pc'

-- 2.
SELECT p.maker, p.model, p.type
FROM product AS p
LEFT JOIN pc AS pc ON p.model = pc.model
LEFT JOIN laptop AS l ON p.model = l.model
LEFT JOIN printer AS pr ON p.model = pr.model
WHERE pc.price IS NULL AND l.model IS NULL AND pr.model IS NULL

---------------------------------------

-- 1.
SELECT s.NAME, c.COUNTRY, c.NUMGUNS, s.LAUNCHED
FROM CLASSES AS c
JOIN SHIPS AS s ON s.CLASS = c.CLASS

-- 2.
SELECT DISTINCT o.SHIP
FROM OUTCOMES AS o
JOIN BATTLES AS b ON b.NAME = o.BATTLE
WHERE YEAR(b.DATE) = 1942