SELECT MODEL, SPEED AS MHz, HD AS GB
FROM PC
WHERE PRICE < 1200;

SELECT MODEL, PRICE / 1.1 AS PRICE_EUR
FROM LAPTOP
ORDER BY PRICE_EUR ASC;

SELECT MODEL, RAM, SCREEN
FROM LAPTOP
WHERE PRICE > 1000;

SELECT *
FROM PRINTER
WHERE COLOR = 'y';

SELECT MODEL, SPEED, HD
FROM PC
WHERE (CD = '12x' OR CD = '16x') AND PRICE < 2000;

SELECT CODE, MODEL, (SPEED + RAM + 10 * SCREEN) AS RATING
FROM LAPTOP
ORDER BY RATING DESC, CODE ASC;