SELECT Class, Country
FROM CLASSES
WHERE NUMGUNS < 10;

SELECT NAME AS shipName
FROM SHIPS
WHERE LAUNCHED < 1918;

SELECT Ship, Battle
FROM OUTCOMES
WHERE RESULT = 'sunk';

SELECT Name
FROM SHIPS
WHERE NAME = CLASS;

SELECT Name
FROM SHIPS
WHERE NAME LIKE 'R%';

SELECT Name
FROM SHIPS
WHERE NAME LIKE '% %' AND NAME NOT LIKE '% % %';